import { DeliveryType, OrderStatus, PaymentType } from '@common/enums/Order';

/** Aggregated counter for a bucket of orders. */
export interface MetricBucket {
  /** Number of orders in the bucket. */
  count: number;
  /** Qualifying revenue generated by the bucket. */
  revenue: number;
}

/** Breakdown of revenue/orders by payment method. */
export type PaymentBreakdown = Record<keyof typeof PaymentType, MetricBucket>;

/** Breakdown of revenue/orders by delivery method. */
export type DeliveryBreakdown = Record<keyof typeof DeliveryType, MetricBucket>;

/** Number of orders in each lifecycle status. */
export type StatusBreakdown = Record<keyof typeof OrderStatus, number>;

/** High-level KPIs for the selected period. */
export interface StatisticsSummary {
  /** Echo of the resolved reporting period. */
  period: { startDate: string | null; endDate: string | null };
  /** Total number of orders placed in the period (all statuses). */
  totalOrders: number;
  /** Number of orders that count as earned (delivered or successfully paid online). */
  completedOrders: number;
  /** Number of cancelled orders in the period. */
  cancelledOrders: number;
  /** Ratio of cancelled orders to total orders (0..1). */
  cancellationRate: number;
  /** Sum of `total` over qualifying (earned) orders. */
  revenue: number;
  /** Average value of a qualifying order (revenue / completedOrders). */
  averageOrderValue: number;
  /** Sum of discounts granted on qualifying orders. */
  totalDiscount: number;
  /** Number of qualifying orders that used a promo code. */
  ordersWithPromo: number;
  /** Revenue/orders split by payment method. */
  payments: PaymentBreakdown;
  /** Convenience cash vs non-cash (card + online) split. */
  cashVsNonCash: { cash: MetricBucket; nonCash: MetricBucket };
  /** Revenue/orders split by delivery method. */
  delivery: DeliveryBreakdown;
  /** Order counts per lifecycle status. */
  statusBreakdown: StatusBreakdown;
}

/** A single month row of the monthly time series. */
export interface MonthlyStatsRow {
  /** Month key in `YYYY-MM` form (reporting timezone). */
  month: string;
  orders: number;
  revenue: number;
  cashCount: number;
  nonCashCount: number;
}

/** A single weekday row (Monday → Sunday). */
export interface WeekdayStatsRow {
  /** ISO weekday number, 1 = Monday … 7 = Sunday. */
  weekday: number;
  /** Human-readable weekday name. */
  name: string;
  orders: number;
  revenue: number;
}

/** A single hour-of-day row for the peak-hours heatmap. */
export interface HourStatsRow {
  /** Hour of day, 0–23 (reporting timezone). */
  hour: number;
  orders: number;
}

/** A single best-selling product row. */
export interface TopProductRow {
  productId: string | null;
  name: string | null;
  /** Total units sold across all orders in the period. */
  quantitySold: number;
  /** Revenue attributed to the product (Σ quantity × price). */
  revenue: number;
}
